name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.2'
    - run: |
        bash ./build.sh
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      id: create_release
      with:
        repo_token: ${{secrets.TOKEN}}
        automatic_release_tag: "latest"
        prerelease: false:
        title: "Caddy2 latest"
        files: |
          caddy
